version: '3'
services:
  jupyter01:
    image: chayapan/thesis:v1.0
    container_name: thesis-nb1
    environment:
      - PASSWORD=chayapan
    ports:
      - 8001:8888
    volumes:
      - .:/home/jovyan
      # Mount data from FS
      # - ./thesis-dataset:/dataset
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
