version: '3'
services:
  jupyter01:
    image: chayapan/thesis:v1.0
    container_name: thesis-nb1
    environment:
      - PASSWORD=chayapan
    ports:
      - 8001:8888
    volumes:
      - .:/opt/workspace
      - ./jupyter_notebook_config.py:/home/.jovyan/jupyter_notebook_config.py
      # Mount data from FS
      # - ./thesis-dataset:/dataset
    networks:
      - mynet
  jupyter02:
    image: chayapan/jupyterlab
    container_name: lab1
    ports:
      - 8888:8888
    volumes:
      - .:/opt/workspace
networks:
  mynet:
    driver: bridge
